### PR TITLE
chore: add docs and project settings

### PR DESCRIPTION
**Pull request by tisonkun**
cc @sundy-li 

Also I wonder if we can release a 1.0.0 to note the stability of this lib, or there is any blocker for 1.0.

### CODE REVIEW

**Comment by sundy-li** [comment]
There is no blocker for 1.0.

But I found there is already a function in std lib to implement `partial_sort`.

https://doc.rust-lang.org/std/primitive.slice.html#method.select_nth_unstable

**Comment by tisonkun** [comment]
@sundy-li Thanks for your response.

[`select_nth_unstable`](https://doc.rust-lang.org/std/primitive.slice.html#method.select_nth_unstable) seems like partition instead of partial sort?

For example, `partial_sort([-5, 4, 2, -3, 1], 2)` would always give `[-5, -3, 1, ?, ?]`. But `select_nth_unstable([-5, 4, 2, -3, 1], 2)` can give `[-3, -5, 1, ?, ?]`.

**Comment by sundy-li** [comment]
> select_nth_unstable([-5, 4, 2, -3, 1], 2) can give [-3, -5, 1, ?, ?].

Yes, we can combine it with sort_unstable
eg:
```
  let (p, _, _) = permutations.select_nth_unstable_by(limit, cmpare);
  p.sort_unstable_by(c);
```

The time complexity is about `O(k * log(k) * n)`.

`Partial sort`  complexity is about `O(n log k)`


`Partial sort` is still faster.

**Comment by tisonkun** [comment]
That's it. So partial_sort can still provide value.

BTW, we may find another way to run grcov. Or I personally don't think coverage is significant and we can remove the workflow ..

**Comment by sundy-li** [comment]
Let's remove the useless workflow in this pr!

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
Thanks for the contribution.

**Pull request merged**
